name: app
description: A Flutter app for smart fuel station with Firebase integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # UI + charts
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
