// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMKygtfNMpNGIQ1mGgiQMV_SSV0626hWE',
    appId: '1:58838765654:ios:b73a41cd443474e0abebf7',
    messagingSenderId: '58838765654',
    projectId: 'fuelstation-f7e00',
    storageBucket: 'fuelstation-f7e00.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqSetnsDzc2aOUHxIXigHocOfOEGHCNQ4',
    appId: '1:58838765654:web:99a3c68d6c021640abebf7',
    messagingSenderId: '58838765654',
    projectId: 'fuelstation-f7e00',
    authDomain: 'fuelstation-f7e00.firebaseapp.com',
    storageBucket: 'fuelstation-f7e00.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMKygtfNMpNGIQ1mGgiQMV_SSV0626hWE',
    appId: '1:58838765654:ios:b73a41cd443474e0abebf7',
    messagingSenderId: '58838765654',
    projectId: 'fuelstation-f7e00',
    storageBucket: 'fuelstation-f7e00.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZwdJrPcdspJI5BZPLBem4kKGAsmIxGU',
    appId: '1:58838765654:android:b9090a29deaf42ebabebf7',
    messagingSenderId: '58838765654',
    projectId: 'fuelstation-f7e00',
    storageBucket: 'fuelstation-f7e00.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqSetnsDzc2aOUHxIXigHocOfOEGHCNQ4',
    appId: '1:58838765654:web:a64760c4308f844fabebf7',
    messagingSenderId: '58838765654',
    projectId: 'fuelstation-f7e00',
    authDomain: 'fuelstation-f7e00.firebaseapp.com',
    storageBucket: 'fuelstation-f7e00.firebasestorage.app',
  );

}