import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

import 'login_screen.dart'; // Replace with your login screen

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Fuel Station',
      theme: ThemeData(
        primarySwatch: Colors.teal,
      ),
      home: LoginScreen(), // Replace with your actual login screen class
    );
  }
}
